---
defaults:
    tmpdir: /tmp

backups:
  - type: database
    url: postgres://postgres:{env[POSTGRES_PASSWORD]}@127.0.0.1:5432/{env[POSTGRES_DB]}
    to: [bucket1]
    name: postgres-{mm}-{dd}.sql
    tags: postgres

vaults:
  bucket1:
    service: s3
    region: eu-central-1
    name: "{env[S3_BUCKET]}"
...
