name: Publish release

on:
  release:
    types:
      - published
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TWINE_NON_INTERACTIVE: "true"
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      -
        name: Install dependencies
        run: |
          python3 -m venv ./venv && \
          source venv/bin/activate && \
          pip install --upgrade pip && \
          pip install --upgrade build && \
          pip install twine
      -
        name: Build and release
        run: |
          source venv/bin/activate && \
          python -m build && \
          python -m twine check dist/*
